// react-version/src/components/DisplayBranch.js

import '../styles/DisplayBranch.css';
import dounts_2 from '../images/dounts_2.jpeg';

const DisplayBranch = ({ showBranch, city }) => {
    return (
        <div className='cards-container'>
            {showBranch[0] && (
                <div className='card'>
                    <h1>{`${showBranch[0].branch} - ${city[0].cityName}`}</h1>
                    <p>Address: {showBranch[0].address}</p>
                    <p>Phone: {showBranch[0].phone}</p>
                    <img src={dounts_2} alt='dounts' className='image'/>
                    <p className='text' style={{ fontWeight: 'bold' }}>No Image</p>
                </div>
            )}
        </div>
    )
};

export default DisplayBranch;

// vue-version/src/components/DisplayBranch.vue
<template>
    <div>
        <div class="card">
            <h1>{{ branch.branch + " - " + currentCity.cityName}}</h1>
            <p>address: {{ branch.address }}</p>
            <p>phone: {{ branch.phone }}</p>
            <img src="../images/dounts_2.jpeg">
            <p class="text">No Image</p>
        </div>
    </div>
</template>

<script>
export default {
    name: "DisplayBranch",
    props: ["branch", "currentCity"] 
}
</script>


<style scoped>
    .card {
        display: flex;
        flex-direction: column;
        justify-content: flex-start;
        text-align: center;
        margin: 5em;
    }
    img {
         height: 15em;
        width: 17em;
        align-self: center;
        margin-top: 50px;
        border: 0.5px solid black;
        padding: 5em;
        background-color: antiquewhite;
        opacity: 0.5;
    }
    .text {
        position: relative;
        bottom: 5.5em;
        font-weight: bold;
    }
    
</style>
