// vue-version/src/components/SearchBar.vue
<template>
    <div>
        <div>
            <label for="area">Area:</label>
            <select id="area" @change="handleArea">
                <option></option>
                <option 
                    :value= "ar.id"
                    v-for="ar in areas"
                    :key="ar.id"
                >
                    {{ ar.name }}
                </option>
            </select>
            <label for="city">City:</label>
            <select id="city" @change="handleCity">
                <option>choose city</option>
                <option
                    :value="city.id"
                    v-for="city in selectableCities"
                    :key="city.id"
                >
                    {{ city.cityName }}
                </option>
            </select>
        </div>
        <button @click="handleSearch">Search</button>
        <DisplayBranch v-bind:branch="branch" v-bind:currentCity="currentCity" v-if="display === true"/>
    </div>
</template>


<script>
import areasJson from '../data/areas.json';
import citiesJson from '../data/cities.json';
import branchesJson from '../data/branches.json';
import DisplayBranch from './DisplayBranch.vue';

export default {
    name: 'SearchBar',
    data() {
        return {
            areas: [],
            cities: [],
            branchesList: [],
            selectableCities: [],
            selectedCityId: '',
            display: false,
            branch: [],
            currentCity: []

        }
    },
    methods: {
        handleArea(e) {
            const { value } = e.target;
            const findCities = this.cities.filter((city) => {
            if(city.area === value) return city
        });
            this.selectableCities = findCities;
        },
        handleCity(e) {
            const { value } = e.target;
            this.selectedCityId = value;
        },
        handleSearch() {
            const findBranch = this.branchesList.filter((x) => {
                return x.cityId === this.selectedCityId
            });
            const find = this.selectableCities.filter( (x) => { return x.id === findBranch[0].cityId});
            this.currentCity = find[0];
            this.display = true;
            this.branch = findBranch[0];

        }
    },
    created() {
        this.areas = areasJson;
        this.cities = citiesJson;
        this.branchesList = branchesJson;
    },
    components: {
        DisplayBranch
    }
}
</script>

<style scoped>
    h1 {
       color: blueviolet; 
    }
</style>

// react-version/src/components/SearchBar.js
import React, { useState, useEffect } from 'react';
import areas from '../data/areas.json';
import cities from '../data/cities.json';
import branches from '../data/branches.json';
import DisplayBranch from './DisplayBranch';
import '../styles/SearchBar.css';


const SearchBar = () => {
    const [areasList,setAreasList] = useState([]);
    const [citiesList,setCitiesList] = useState([]);
    const [selecableCities,setSelectableCities] = useState([]);
    const [selectedBranch,setSelectedBranch] = useState(null);
    const [showBranch,setShowBranch] = useState('');
    const [city,setCity] = useState('');

    
    useEffect(() => {
        setAreasList(areas);
        setCitiesList(cities);
    },[])


    const handleSelectedArea = (e) => {
        const { value } = e.target;
        const findCities = citiesList.length > 0 && citiesList.filter((city) => {
            return city.area === value
        });
        setSelectableCities(findCities);
    };

    const handleSelectedCity = (e) => {
        const { value } = e.target;
        setSelectedBranch(value);
    };

    const handleSearchBranchInfo = () => {
        const display = branches.length > 0 && branches.filter((br) => {
            return br.cityId === selectedBranch
        });

        setShowBranch(display);
        const find = selectedBranch && citiesList.filter( (x) => { return x.id === selectedBranch});
        setCity(find)
    }


    return (
        <>
            <div className='s-container' style={{ padding: 100 , marginTop: 50, width: '70%'}}>
                <div className='s-inputs'>
                    <label htmlFor='area' style={{ fontWeight: 'bold' }}>Area: </label>
                    <select 
                        name='area' 
                        onChange={handleSelectedArea} 
                        style={{ padding: 10, width: 150, fontSize: 16, marginRight: 80 }}
                    >
                        <option></option>
                        {areasList.length > 0  && areasList.map((item) => {
                            return (
                                <option 
                                    id='' 
                                    key={item.id}
                                    value={item.id} 
                                >
                                    {item.name}
                                </option>
                            )
                        })}
                    </select>

                    <label htmlFor='city' style={{ fontWeight: 'bold' }}>City: </label>
                    <select 
                        name='city' 
                        onChange={handleSelectedCity} 
                        style={{ padding: 10, width: 150, fontSize: 16 }}
                    >
                        <option>{selecableCities.length > 0 ? 'choose city' : ''}</option>
                        {selecableCities.length > 0 ? selecableCities.map((city) => {
                            return (
                            <option
                                key={city.id}
                                value={city.id}
                            >
                                {city.cityName}
                            </option>
                            )
                        }) : (
                            <option></option>
                        )}
                    </select>
                </div>
                <button 
                    onClick={handleSearchBranchInfo} 
                    style={{ fontStyle: 18, fontWeight: 'bold' }}
                    className='button'
                    disabled={selecableCities.length > 0 ? false : true}
                >
                    Search
                </button>
            </div>
            <DisplayBranch showBranch={showBranch} city={city}/>
        </>
    )
};

export default SearchBar;
